import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // routeTree.gen.ts is generated by the TanStack Start Vite plugin.
  { ignores: ["node_modules/**", ".output/**", ".tanstack/**", "src/routeTree.gen.ts"] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@workspace/*-db", "!@workspace/collaboration-db"],
              message:
                "Boundary violation: apps/collaboration may only import its own database package (@workspace/collaboration-db). Access other domains via API or events.",
            },
          ],
        },
      ],
    },
  }
);
