import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // routeTree.gen.ts is generated by the TanStack Start Vite plugin.
  { ignores: ["node_modules/**", ".output/**", ".tanstack/**", "src/routeTree.gen.ts"] },
  js.configs.recommended,
  ...tseslint.configs.recommended
);
